<a href="https://colab.research.google.com/github/ibrohim747/MathInPython/blob/main/005_Algebra_1/003_MetricesWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [7]:
A = np.array([[1,2],[3,4]])

print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [8]:
mat = np.zeros([4,6])
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
mat[0,1] = 2
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
mat[2,4] = 7
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
x = sym.symbols('x')
y = sym.symbols('y')

fm = sym.matrices.Matrix([[2,3],[4,5]])
fm2 = sym.matrices.Matrix([x, y])
display(Math(sym.latex(sym.sympify(fm))))
display(Math(sym.latex(sym.sympify(fm2))))
fm3 = fm * fm2
display(Math(sym.latex(sym.sympify(fm3))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [16]:
fm = np.array([[2,3],[4,1]])
fm2 = np.array([4,8])

display(Math(sym.latex(sym.sympify(fm))))
display(Math(sym.latex(sym.sympify(fm2))))

fm3 = fm * fm2
display(Math(sym.latex(sym.sympify(fm3))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [21]:
numrange = range(0,2)

for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)
mat

array([[ 1., -1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  7.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [25]:
x, y = sym.symbols('x y')
Fxy = (4+x)*(2-y)
display(Math(sym.latex(Fxy)))

xyset = range(0,3)

outmat = np.zeros([len(xyset), len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i, y:j})

display(Math(sym.latex(sym.sympify(outmat))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>